Verilator 3.900 2017-01-15 rev verilator_3_890-15-ge6d7e7e Needed to be added around lines 29 & 65 in sdram_test.v file +/* verilator lint_off UNUSED */  input master_clk_i; +/* verilator lint_off UNUSED */
+/* verilator lint_off UNUSED */
+reg o_TX_Done;
+/* verilator lint_off UNUSED */
make
-- RUN ---------------------
obj_dir/Vsdram_test +trace
Enabling waves into logs/vlt_dump.vcd...
/home/pi/sdram_tests/verilated/obj_dir/Vsdram_test
/home/pi/sdram_tests/verilated/logs/vlt_dump.vcd
Needed to kill after 20 sec vcd file gets to big
ps -ax | grep Vsdram_test
kill -9 xxxx

Verilator 3.923 devel rev UNKNOWN_REV
make
Vsdram_test__ALL.a(Vsdram_test__ALLsup.o): In function `Vsdram_test::traceInit(VerilatedVcd*, void*, unsigned int)':
Vsdram_test__ALLsup.cpp:(.text+0x1514): undefined reference to `VL_FATAL_MT(char const*, int, char const*, char const*)'
collect2: error: ld returned 1 exit status
Vsdram_test.mk:63: recipe for target 'Vsdram_test' failed
make[1]: *** [Vsdram_test] Error 1